### ISSUE TITLE
update-binfmts: warning: Couldn't load the binfmt_misc module

### ISSUE THREAD

**Issue by SayidHosseini** [rmoriz/multiarch-test#2]
While the `post_checkout` script is being run, we attempt to install `curl binfmt-support qemu-user-static jq moreutils`. In the process, we observe this message several times:

**`update-binfmts: warning: Couldn't load the binfmt_misc module`**

I tested the output and they work fine on all platforms; and this is a non fatal warning. However, I'm not sure how important this is.

I tried to fix it by adding `mount binfmt_misc -t binfmt_misc /proc/sys/fs/binfmt_misc/` before the package installations, but I get `permission denied` and the build is failed!

Appreciate any help!

**Comment by rmoriz** [comment]
I think this is an Ubuntu issue or caused by the qemu-static package that registeres handlers by default.

**Comment by rmoriz** [comment]
FYI: my repo https://github.com/rmoriz/openra-dockerfile contains a newer version of this setup tailored to a real project. (last tested end of November 2019 though)

**Comment by SayidHosseini** [comment]
Any way to work around it?

**Comment by SayidHosseini** [comment]
I tested your latest setup you `openra`; however the same thing happen.

**Comment by rmoriz** [comment]
If you want to debug it, try it on plain amd64 Ubuntu locally. I'm rather sure it's not an issue that is caused by Dockerhub's CI.

**Comment by patrickdk77** [comment]
This is a non-issue, unless your running this locally.

dockerhub builds run in a container that doesn't have permission to update binfmt so this error is expected. Could experiment with it not being needed and then skipped if running in a docker/lxc/... enviroment where it wouldn't be used. But this is probably just best to ignore.
