### ISSUE TITLE
.config is out of date

### ISSUE THREAD

**Issue by raetha** [rmoriz/multiarch-test#4]
Hi @rmoriz,

First I want to say thank you so much for creating this. I'm new to the world of Docker Hub and GitHub, but have been working on a quick home project recently using both. I was struggling to figure out the multi-arch support and this project worked perfectly to get me going.

What I wanted to let you know though was that it looks like you recently resynced your hooks folder with another working project, but missed the ".config" file. The error was quickly obvious and I manually copied the changes into my repo and it worked, but you likely want to sync it here as well.

Thanks,
-Raetha

**Comment by rmoriz** [comment]
thanks. I've updated the .config file now
